[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
authors = ["aecsocket <aecsocket@tutanota.com>"]
categories = []
edition = "2024"
keywords = []
license = "MIT OR Apache-2.0"
repository = "https://github.com/aecsocket/wordbase"
rust-version = "1.85.0"

[workspace.lints.rust]
# missing_docs = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(fuzzing)'] }

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

unwrap_used = "warn"

module_name_repetitions = "allow"
needless_pass_by_value = "allow"
similar_names = "allow"
too_many_arguments = "allow"
type_complexity = "allow"

missing_errors_doc = "allow"

[workspace.dependencies]
wordbase = { path = "crates/wordbase", default-features = false }
wordbase-client-tokio = { path = "crates/wordbase-client-tokio", default-features = false }

anyhow = "1.0"
bzip2 = "0.5"
clap = "4.5"
derive_more = "2.0"
foldhash = "0.1.4"
futures = "0.3"
indexmap = "2.7"
itertools = "0.14.0"
serde-value = "0.7.0"
zip = "2.2"

form_urlencoded = { version = "1.2", default-features = false }
glib = { version = "0.20", default-features = false }
gtk4 = { version = "0.9", default-features = false }
html-escape = { version = "0.2", default-features = false }
libadwaita = { version = "0.7", default-features = false }
log = { version = "0.4" }
mecab = { version = "0.1.6", default-features = false }
open = { version = "5.3", default-features = false }
pretty_env_logger = { version = "0.5" }
rayon = { version = "1.10", default-features = false }
regex = { version = "1.11", default-features = false }
rmp-serde = { version = "1.3", default-features = false }
serde = { version = "1.0", default-features = false }
serde_json = { version = "1.0", default-features = false }
serde_repr = { version = "0.1", default-features = false }
sqlx = { version = "0.8", default-features = false }
tokio = { version = "1.43", default-features = false }
tokio-tungstenite = { version = "0.26", default-features = false }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false }
webkit6 = { version = "0.4", default-features = false }

[workspace.metadata.cargo-shear]
ignored = ["bzip2"]
