[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
authors = ["aecsocket <aecsocket@tutanota.com>"]
categories = []
edition = "2024"
keywords = []
license = "MIT OR Apache-2.0"
repository = "https://github.com/aecsocket/wordbase"
rust-version = "1.85.0"

[workspace.lints.rust]
# missing_docs = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(fuzzing)'] }

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

unwrap_used = "warn"

module_name_repetitions = "allow"
needless_pass_by_value = "allow"
similar_names = "allow"
too_many_arguments = "allow"
type_complexity = "allow"

missing_errors_doc = "allow"

[workspace.dependencies]
wordbase = { path = "crates/wordbase", default-features = false }
wordbase-client-tokio = { path = "crates/wordbase-client-tokio", default-features = false }

anyhow = "1.0"
bzip2 = "0.5"
clap = "4.5"
derive_more = "2.0"
foldhash = "0.1.4"
form_urlencoded = "1.2"
futures = "0.3"
glib = "0.20"
gtk4 = "0.9"
html-escape = "0.2"
indexmap = "2.7"
libadwaita = "0.7"
log = "0.4"
mecab = "0.1.6"
open = "5.3"
pretty_env_logger = "0.5"
rayon = "1.10"
regex = "1.11"
rmp-serde = "1.3"
serde = "1.0"
serde_json = "1.0"
serde_repr = "0.1"
sqlx = "0.8"
tokio = "1.43"
tokio-tungstenite = "0.26"
tracing = "0.1"
tracing-subscriber = "0.3"
webkit6 = "0.4"
zip = "2.2"

[workspace.metadata.cargo-shear]
ignored = ["bzip2"]
