[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
authors = ["aecsocket <aecsocket@tutanota.com>"]
categories = []
edition = "2024"
keywords = []
license = "MIT OR Apache-2.0"
repository = "https://github.com/aecsocket/wordbase"
rust-version = "1.85.0"

[workspace.lints.rust]
missing_docs = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(fuzzing)"] }

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

unwrap_used = "warn"

module_name_repetitions = "allow"
type_complexity = "allow"

[workspace.dependencies]
wordbase = { path = "crates/wordbase" }
wordbase-client-tokio = { path = "crates/wordbase-client-tokio" }
wordbase-server = { path = "crates/wordbase-server" }

anyhow = "1.0"
ascii_table = "4.0"
bzip2 = "0.5"
cfg-if = "1.0"
clap = "4.5"
derive_more = "2.0"
foldhash = "0.1.4"
form_urlencoded = "1.2"
futures = "0.3"
glib = "0.20"
gtk4 = "0.9"
html-escape = "0.2"
indexmap = "2.7"
libadwaita = "0.7"
lindera = "0.39"
maud = "0.27"
mecab = "0.1.6"
open = "5.3"
rand = "0.9"
rayon = "1.10"
regex = "1.11"
rmp-serde = "1.3"
serde = "1.0"
serde_json = "1.0"
serde_repr = "0.1"
sqlx = "0.8"
tokio = "1.43"
tokio-tungstenite = "0.26"
tracing = "0.1"
tracing-subscriber = "0.3"
webkit6 = "0.4"
zbus = { version = "5.5", default-features = false }
zip = "2.2"

[workspace.metadata.cargo-shear]
ignored = ["bzip2"]
