[package]
name = "wordbase-storage"

authors.workspace      = true
categories.workspace   = true
edition.workspace      = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
wordbase-api = { workspace = true }

async-channel = { workspace = true }
bytes         = { workspace = true }
eyre          = { workspace = true }
tracing       = { workspace = true }
