[package]
name = "wordbase-cli"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
anyhow = { workspace = true }
ascii_table = { workspace = true, features = ["wide_characters"] }
clap = { workspace = true, features = ["derive"] }
futures = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
wordbase = { workspace = true, features = ["desktop"] }

[lints]
workspace = true
