[package]
name = "wordbase-sys"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[package.metadata.docs.rs]
all-features = true

[lib]
crate-type = ["cdylib"]
doc = false
name = "wordbase"

[dependencies]
android_logger = { workspace = true, optional = true }
tracing = { workspace = true }
wordbase-engine = { workspace = true, features = ["uniffi"] }

[features]
android = ["dep:android_logger", "tracing/log-always"]

[lints]
workspace = true
