[package]
name = "wordbase-sys"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[package.metadata.docs.rs]
all-features = true

[lib]
crate-type = ["cdylib"]
doc = false
name = "wordbase"

[dependencies]
wordbase = { workspace = true, features = ["uniffi"] }

[features]
android = ["wordbase/android"]

[lints]
workspace = true
