[package]
name = "wordbase-gtk"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Dictionary and word lookup service - GTK application"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
all-features = true

[package.metadata.cargo-shear]
ignored = [
  "bzip2",  # to enable transitive dependency features
]

[dependencies]
anyhow = { workspace = true }
arc-swap = { workspace = true }
ashpd = { workspace = true, features = ["gtk4"] }
bimap = { workspace = true }
bytes = { workspace = true }
bzip2 = { workspace = true, features = ["static"] }
data-encoding = { workspace = true }
derive_more = { workspace = true, features = ["display"] }
directories = { workspace = true }
foldhash = { workspace = true }
form_urlencoded = { workspace = true }
futures = { workspace = true }
gio = { workspace = true }
glib = { workspace = true, features = ["log"] }
gtk4 = { workspace = true, features = ["blueprint", "gnome_47"] }
indexmap = { workspace = true }
libadwaita = { workspace = true, features = ["v1_7"] }
libspa = { workspace = true }
maud = { workspace = true }
notify = { workspace = true }
pipewire = { workspace = true }
rand = { workspace = true }
relm4 = { workspace = true, features = ["gnome_47", "libadwaita"] }
relm4-icons = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio", "sqlite"] }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
webkit6 = { workspace = true }
wordbase = { workspace = true }
wordbase-desktop = { workspace = true }
zbus = { workspace = true, features = ["tokio"] }

[build-dependencies]
relm4-icons-build = { workspace = true }

[lints]
workspace = true
