[package]
name = "wordbase-api"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Dictionary and word lookup service - API types"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
bytes = { workspace = true, features = ["serde"] }
data-encoding = { workspace = true, optional = true }
derive_more = { workspace = true, features = [
  "debug",
  "deref",
  "deref_mut",
  "display",
  "error",
  "from",
] }
itertools = { workspace = true }
maud = { workspace = true, optional = true }
paste = { workspace = true }
poem = { workspace = true, optional = true }
poem-openapi = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uniffi = { workspace = true, optional = true }

[features]
poem = ["dep:poem", "dep:poem-openapi"]
render-html = ["dep:maud"]
uniffi = ["dep:data-encoding", "dep:uniffi"]

[lints]
workspace = true
