[package]
description = "Dictionary and word lookup service - shared desktop logic"
name        = "wordbase-desktop"
version     = "0.1.0"

authors.workspace      = true
categories.workspace   = true
edition.workspace      = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
# http = ["wordbase/poem", "dep:async-stream", "dep:poem", "dep:poem-openapi"]
http = []

[dependencies]
wordbase-api    = { workspace = true }
wordbase-engine = { workspace = true }

async-channel     = { workspace = true }
async-stream      = { workspace = true, optional = true }
bytes             = { workspace = true }
directories       = { workspace = true }
eyre              = { workspace = true }
futures           = { workspace = true }
poem              = { workspace = true, optional = true, features = ["anyhow"] }
poem-openapi      = { workspace = true, optional = true, features = ["swagger-ui"] }
serde_json        = { workspace = true }
tokio             = { workspace = true, features = ["net", "time"] }
tokio-tungstenite = { workspace = true }
tokio-util        = { workspace = true, features = ["rt"] }
tracing           = { workspace = true }
