[package]
name = "wordbase-core-deinflect"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
eyre = { workspace = true }
itertools = { workspace = true }
lindera = { workspace = true }
unicode-segmentation = { workspace = true, optional = true }
wordbase-core = { workspace = true }

[dev-dependencies]
indexmap = { workspace = true }

[features]
all-deinflectors = ["deinflector-latin"]
deinflector-latin = ["dep:unicode-segmentation"]

[lints]
workspace = true
