[package]
description = "Dictionary and word lookup service - API types"
name = "wordbase"
version = "0.1.0"

authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
parse-yomitan = ["dep:rayon", "dep:regex", "dep:zip"]
render-html = ["dep:maud", "dep:html-escape", "dep:indexmap"]

[dependencies]
derive_more = { workspace = true, features = [
  "from",
  "display",
  "error",
  "deref",
  "deref_mut",
] }
foldhash = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_repr = { workspace = true }

html-escape = { workspace = true, optional = true }
indexmap = { workspace = true, optional = true }
maud = { workspace = true, optional = true }

rayon = { workspace = true, optional = true }
regex = { workspace = true, optional = true }
zip = { workspace = true, optional = true }
