[package]
name = "wordbase"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Dictionary and word lookup service"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
android_logger = { workspace = true, optional = true }
anyhow = { workspace = true }
arc-swap = { workspace = true }
async-compression = { workspace = true, features = ["xz"] }
async-stream = { workspace = true }
async-tar = { workspace = true }
async_zip = { workspace = true, features = ["deflate", "tokio"] }
bytes = { workspace = true }
data-encoding = { workspace = true }
derive_more = { workspace = true, features = [
  "debug",
  "deref",
  "deref_mut",
  "display",
  "error",
  "from",
] }
directories = { workspace = true, optional = true }
distance = { workspace = true }
foldhash = { workspace = true }
futures = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
itertools = { workspace = true }
jmdict-furigana = { workspace = true }
lindera = { workspace = true, features = ["compress", "unidic"] }
maud = { workspace = true }
paste = { workspace = true }
pin-project = { workspace = true }
regex = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
serde_repr = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio", "sqlite"] }
tera = { workspace = true, features = ["preserve_order"] }
tokio = { workspace = true, features = ["macros", "sync"] }
tokio-stream = { workspace = true }
tokio-tungstenite = { workspace = true, optional = true }
tokio-util = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
unicode-segmentation = { workspace = true }
uniffi = { workspace = true, features = ["tokio"], optional = true }
wordbase-api = { workspace = true, features = ["render-html"] }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[features]
android = ["dep:android_logger", "tracing/log-always"]
desktop = ["dep:directories", "dep:tokio-tungstenite"]
poem = ["wordbase-api/poem"]
uniffi = ["dep:uniffi", "wordbase-api/uniffi"]

[lints]
workspace = true
