[package]
description = "Dictionary and word lookup service"
name = "wordbase"
version = "0.1.0"

authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
parse-yomitan = ["dep:rayon", "dep:regex", "dep:zip"]

[dependencies]
derive_more = { workspace = true, features = [
    "from",
    "display",
    "error",
    "deref",
    "deref_mut",
] }
foldhash = { workspace = true }
html-escape = { workspace = true }
maud = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_repr = { workspace = true }

rayon = { workspace = true, optional = true }
regex = { workspace = true, optional = true }
zip = { workspace = true, optional = true }
