[package]
name = "wordbase-core"

authors.workspace      = true
categories.workspace   = true
edition.workspace      = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
poem = ["wordbase-types/poem"]
rkyv = ["wordbase-types/rkyv"]

[dependencies]
wordbase-types = { workspace = true, features = ["serde"] }

async-channel = { workspace = true }
bytes         = { workspace = true }
eyre          = { workspace = true }
rayon         = { workspace = true }
serde         = { workspace = true, features = ["derive"] }
serde_json    = { workspace = true }
tokio         = { workspace = true, features = ["rt", "fs"] }
tracing       = { workspace = true }
