[package]
name = "wordbase-core"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
async-channel = { workspace = true }
bytes = { workspace = true }
eyre = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["fs", "rt"] }
tracing = { workspace = true }
wordbase-types = { workspace = true, features = ["serde"] }

[features]
poem = ["wordbase-types/poem"]
rkyv = ["wordbase-types/rkyv"]

[lints]
workspace = true
