//! See [`Deinflector`].

use {
    eyre::Result,
    std::{any::type_name, borrow::Cow, fmt::Debug, ops::Range},
};

/// Reads text of arbitrary length and generates [`Deinflection`]s for use in
/// lookups.
///
/// Each generated [`Deinflection::lemma`] will be looked up using
/// [`LookupStorage`] to find appropriate records for the word, so it's OK if
/// the generated lemma is potentially not a real lemma, and therefore may not
/// have results in the storage. False positives are better than false negatives
/// in this case.
///
/// [`LookupStorage`]: crate::storage::LookupStorage
pub trait Deinflector: Send + Sync + Debug + 'static {
    /// Gets a unique, static, and persistent identifier for this deinflector.
    ///
    /// This is implemented as [`type_name::<Self>`][type_name] by default.
    fn id(&self) -> &'static str {
        type_name::<Self>()
    }

    /// Reads text of arbitrary length and generates [`Deinflection`]s.
    ///
    /// `cursor` is where the user's text cursor is currently located when
    /// looking up a word in this text. This can be used to generate more
    /// accurate lemmas, e.g. seeking backwards from the cursor to find the
    /// start of the word at the cursor.
    ///
    /// # Errors
    ///
    /// Errors if the lemmas could not be generated.
    ///
    /// [`LookupStorage`]: crate::storage::LookupStorage
    fn deinflect<'t>(&self, sentence: &'t str, cursor: usize) -> Result<Vec<Deinflection<'t>>>;
}

/// Deinflection lemma generated by [`Deinflector::deinflect`].
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Deinflection<'t> {
    /// Canonical, deinflected form of a word.
    ///
    /// A [*lemma*] is the canonical form of a word - the one you would find in
    /// a dictionary, without any inflections like tense. For example, the lemma
    /// of "running", "ran", and "run" is "run".
    ///
    /// This lemma may be looked up using [`LookupStorage::lookup`] to find
    /// appropriate dictionary results for this word.
    ///
    /// [lemma]: https://en.wikipedia.org/wiki/Lemma_%28morphology%29
    /// [`LookupStorage::lookup`]: crate::storage::LookupStorage::lookup
    pub lemma: Cow<'t, str>,
    /// Where in the input text this lemma appears.
    ///
    /// Not that this may not be equivalent to [`Deinflection::lemma`]'s length
    /// if the lemma is not a substring of the input text. For example, in the
    /// input sentence,
    ///
    /// ```text
    /// He is running to the store.
    /// ```
    ///
    /// the word "running" will generate a deinflection for the lemma "run", but
    /// the two strings are not the same length. So the lemma "run" maps to this
    /// segment of the input text:
    ///
    /// ```text
    /// He is running to the store.
    ///       ^^^^^^^
    /// ```
    pub source_span: Range<usize>,
}

impl<'t> Deinflection<'t> {
    /// Creates a new deinflection from a string in the source text, and the
    /// lemma that it generated.
    ///
    /// - `start` is the index of the start of `src` in the source text.
    /// - `src` is the string which deinflects to `lemma`.
    /// - `lemma` is the deinflected form of `src`.
    ///
    /// # Examples
    ///
    /// ```
    /// # use wordbase_core::deinflect::Deinflection;
    /// // assuming you have a source text, and are focusing on a specific word...
    /// let text = "He is running to the store.";
    /// let start = text.find("running").unwrap();
    ///
    /// // ...we generate the deinflection
    /// let deinflection = Deinflection::new(start, "running", "run");
    /// assert_eq!(deinflection.lemma, "run");
    /// assert_eq!(
    ///     deinflection.source_span,
    ///     ("He is ").len()..("He is running".len()),
    /// );
    /// ```
    pub fn new(start: usize, src: &str, lemma: impl Into<Cow<'t, str>>) -> Self {
        let lemma = lemma.into();
        Deinflection {
            source_span: start..(start + src.len()),
            lemma,
        }
    }
}
