on:
  pull_request:
  push:
    branches:
      - main

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    # TODO https://github.com/NixOS/nixfmt/issues/76
    # find a solution
